services:
    turbine.telecash.form.type.gateway_configuration:
        class: Turbine\SyliusTelecashPlugin\Form\Type\TelecashConnectGatewayConfigurationType
        public: true
        tags:
            - { name: sylius.gateway_configuration_type, type: telecash_connect, label: turbine.sylius_telecash_plugin.connect.label }
            - { name: form.type }

    turbine.telecash.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        public: true
        arguments:
            $gatewayFactoryClass: Turbine\SyliusTelecashPlugin\Telecash\Connect\TelecashConnectGatewayFactory
        tags:
            - { name: payum.gateway_factory_builder, factory: telecash_connect }
