# Delete these routes and define your own shop routes here

turbine_sylius_telecash_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: SyliusTelecashPlugin:Greeting:staticallyGreet
        name: ~

turbine_sylius_telecash_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: SyliusTelecashPlugin:Greeting:dynamicallyGreet
        name: ~
